### ISSUE TITLE
mbtiles generated with the tool doesn't work with GeoODK (no images table)

### ISSUE THREAD

**Issue by Sameme** [lutraconsulting/qgis-xyz-tiles#29]
mbtiles file generated with the tool doesn't work in GeoODK app. The reason is the absence of `images table`. See error screenshots below
![2019-07-18](https://user-images.githubusercontent.com/12427102/61475754-70376800-a983-11e9-867c-940241477737.jpg)

-- This is how the file composition look like 
![xyz](https://user-images.githubusercontent.com/12427102/61475940-d15f3b80-a983-11e9-911a-9eefec40b941.PNG)

-- File composition of mbtiles from other sources that work looks like this 

![xyz2](https://user-images.githubusercontent.com/12427102/61475986-eb991980-a983-11e9-9c44-2f4986d8d98e.PNG)

Any suggested solution to resolve this will be highly appreciated.

Thanks

**Comment by saberraz** [comment]
This is more like an issue with GeoODK app than this algorithm. 

Could you try gdalinfo and the tile and attach the output here? Essentially, if it is readable by GDAL, any other application using GDAL driver should be able to read the file.

**Comment by christad92** [comment]
@saberraz thanks for the response. 
This is not an issue with GeoODK but the file composition of the mbtiles. Even when we try to serve it as a WMTS it fails with the same error that it couldn't find the `images` table. It works as a layer within QGIS but not across the multiple platforms where we have previously used GDAL generated mbtiles.

**Comment by saberraz** [comment]
Would it be possible to attach an example file or add the `gdalinfo` output from the file?

**Comment by christad92** [comment]
Here is what the gdalinfo return:
![image](https://user-images.githubusercontent.com/5230530/61560697-e8298f00-aa64-11e9-9985-1ddf3c2f6c1a.png)
![image](https://user-images.githubusercontent.com/5230530/61560726-fe374f80-aa64-11e9-82d4-ee4c4a426bbb.png)

**Comment by saberraz** [comment]
From GeoODK, it appears that they only support vector (???) mbtiles:
https://github.com/GeoODK/collect#main-functionality
(I guess by  "line Layer tiles (MapBox)" they mean vector mbtile).

The XYZ tile generator is for raster mbtiles, which appears not to be supported in GeoODK. Please file a ticket in GeoODK feature request or use https://inputapp.io which is based on QGIS.

**Comment by christad92** [comment]
@saberraz GeoODK supports raster mbtiles because we have used these countless times. However, I have tried serving the mbtiles as WMTS file using portable base map server but it still fails with the same error.
