### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by asfixia** [lutraconsulting/qgis-xyz-tiles#31]
What is this project license?

**Comment by saberraz** [comment]
Added.

**Comment by asfixia** [comment]
saberraz thanks for the fast answer. 

Just one more question, any reason to use GPL instead of MIT?

I am worried about the contamination of GPL if at some point someone uses a GPL license it contaminate all the others projects with it.
About my usage; I am planning to create a QGIS plugin that allows users to publish their maps online for free using free services.
It is in beta development yet, but if you want to take a look https://csrmaps.github.io/.

The plugin i am planning to publish under MIT instead of GPL.

**Comment by saberraz** [comment]
https://github.com/lutraconsulting/qgis-xyz-tiles/blob/master/tiles_xyz/tiles_xyz.py#L37

The algorithm uses QGIS which is GPL, hence we have to use GPL too. This plugin is no longer maintained and incorporated within the QGIS source code.

**Comment by asfixia** [comment]
Ok, you are right! Thanks!

**Comment by saberraz** [comment]
See also QGIS2Web plugin:
https://github.com/tomchadwin/qgis2web

**Comment by asfixia** [comment]
Looks promising, you got the point right, it is very close to what i want.
I will investigate a little deeper to see if there is something usefull in it too.
Thanks again!
Right before the platform launch, i want you to be one of the first to test and give me your opinion, if you interested.

**Comment by saberraz** [comment]
That looks very interesting. We have a similar platform (not free):
https://cloudmappin.com/

**Comment by asfixia** [comment]
Really interesting it seems to be very user friendly and customizable.
And to be honest, the platform idea is really very similar to yours, even the name (mappia).
The biggest difference is that for us every data is treated only as pixels, while for you the data are geographic objects.
