### ISSUE TITLE
Skip blank tiles

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-xyz-tiles#4]
Add an option to avoid outputting the blank tiles.

**Comment by fuggii** [comment]
It should not only skip blank tiles, but try to reload them a given number of times. I have blank tiles all over the map particularly with zoom levels > 10 (affected QGIS versions: 3.4.9 and 3.8.0).

**Comment by DigDigDig** [comment]
Has there been any update on this request?  

I see it was added to milestone: 0.6 but no open or closed issue exists for this request.

**Comment by saberraz** [comment]
This is now a part of the core QGIS Processing. Please file an issue here:
https://github.com/qgis/QGIS/issues
